---
- name: Install logrotate packages
  ansible.builtin.package:
    name: logrotate
    state: present

- name: Deploy custom scripts
  ansible.builtin.template:
    src: logrotate-custom.j2
    dest: "{{ logrotate_conf_dir }}{{ item.name }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ logrotate_scripts }}"


- name: Delete not needed scripts
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ logrotate_scripts_to_remove }}"
