---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: .

  vars:
    logrotate_scripts:
      - name: Exemple
        paths:
          - "/var/log/mail/mail.info"
        frequency: "weekly"
        keep: "52"
        compress: true
        postrotate: "systemctl restart myservice.service > /dev/null"
